# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.shop_login: '_xmlexport'
    app.shop_pass: '6666666'
    app.api_path: 'https://%app.shop_login%:%app.shop_pass%@api2.gifts.ru/export/v2/catalogue/'
    app.catalogue_path: '%app.api_path%catalogue.xml'
    app.stock_path: '%app.api_path%stock.xml'
    app.parser:
        categories:
            1104133:
                name: 'Ручки'
                limit: 5 # Если лимит отсутствует, то выбираются все товары категории
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
